# action.yml
name: "awyes"
description: "Deploy code easily to aws"
inputs:
  path:
    description: "Path to your root project directory"
    required: false
    default: "."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.root }}
