# action.yml
name: "awyes"
description: "Deploy infra trivially to AWS. Yas."
inputs:
  path:
    description: "Path to your awyes.yml file."
    required: false
    default: "./awyes.yml"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
