name: Python Package Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Tag and Deploy New Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install dependencies and package
      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel pipenv twine semver
          pipenv install --system

      # Bump version and create a new tag
      - name: Bump version, create tag and push it
        run: |
          current_version=$(head -n 1 VERSION)
          new_version=$(python -c "import semver; print(semver.bump_patch('$current_version'))")

          echo "Bumping version from $current_version to $new_version"
          echo "$new_version" > VERSION

          git config user.name "trumanpurnell"
          git config user.email "truman.purnell@gmail.com"
          git commit -am "Bump version to $new_version"
          git tag $new_version
          git push origin $new_version

      # Publish the package to PyPI (optional)
      - name: Publish to PyPI
        if: github.ref == 'refs/heads/main'
        env:
          TWINE_USERNAME: trumanpurnell
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
